### ISSUE TITLE
How to apply knowledge

### ISSUE THREAD

**Issue by aguang1201** [conceptofmind/LaMDA-pytorch#5]
Great work. It was mentioned in the paper that it will search for relevant knowledge and use knowledge to answer. Is there a part about knowledge search in this source code?

**Comment by conceptofmind** [comment]
@aguang1201 Unfortunately, I do not have access to a large enough database with a consistent stream of update-to-date information. I was looking into integrating something like pinecone for searching relevant information if the cost was low enough for users.

If you have any recommendations on cost-efficient databases let me know.

Best,

Enrico

**Comment by aguang1201** [comment]
Thanks for your reply, I'm considering using wikipedia api to find relevant knowledge information and integrate it into the conversation to generate a reply

**Comment by conceptofmind** [comment]
@aguang1201 I will have to look into the Wikipedia API as well. If you get something working, feel free to open up a pull request!

Thank you,

Enrico

**Comment by conceptofmind** [comment]
@aguang1201 I found a viable solution utilizing LangChain and SerpApi. I am going to integrate both of them in this library soon.
